version: "3.2"

services:
  linglib:
    image: jekotia/linguisticlibrary
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: linglib
    restart: unless-stopped
    environment:
    - MYSQL_HOST=${LINGLIB_MYSQL_HOST}
    - MYSQL_DATABASE=${LINGLIB_MYSQL_DATABASE}
    - MYSQL_USER=${LINGLIB_MYSQL_USER}
    - MYSQL_PASSWORD=${LINGLIB_MYSQL_PASSWORD}
    volumes:
    #-v Temporary mounting for development purposes v-#
    - ./web:/var/www/html:ro
    depends_on:
    - linglib.database
    networks:
    - proxy
    - linglib
    labels:
      caddy.address: mercury.jekotia.net/linglib/
      caddy.proxy.transparent: ""

  linglib.database:
    image: mysql:5 #:5.6
    container_name: linglib.database
    restart: unless-stopped
    environment:
    - MYSQL_ROOT_PASSWORD=${LINGLIB_MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${LINGLIB_MYSQL_DATABASE}
    - MYSQL_USER=${LINGLIB_MYSQL_USER}
    - MYSQL_PASSWORD=${LINGLIB_MYSQL_PASSWORD}
    volumes:
    - ./linguisticlibrary_v1.sql:/docker-entrypoint-initdb.d/linglib.sql
    networks:
    - linglib

networks:
  proxy:
    external:
      name: core_proxy
  linglib:
